### ISSUE TITLE
Next steps for this project

### ISSUE THREAD

**Issue by YoungiiJC** [Ribbit-Network/api#3]
hey @brianstrauch! I'd like to scope out goals, requirements, etc for this project. And hopefully make some contributions to the code, too.

Can we sync up to review what you've done so far + where this project might be headed? Here's the Ribbit Network discord: https://discord.com/invite/vq8PkDb2TC. I'm _jon.

Thanks for you work so far :)

**Comment by YoungiiJC** [comment]
hi @brianstrauch – following up on this!

**Comment by brianstrauch** [comment]
Sorry for the late response, just replied!
